export default {
    'ARG': 'Argentina',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'BEL': 'Belgium',
    'BGR': 'Bulgaria',
    'BRA': 'Brazil',
    'CAN': 'Canada',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': 'China',
    'COL': 'Colombia',
    'CRI': 'Costa Rica',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DEU': 'Germany',
    'DEW': 'Former Federal Republic of Germany',
    'DNK': 'Denmark',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'FIN': 'Finland',
    'FRA': 'France',
    'GBR': 'United Kingdom',
    'GRC': 'Greece',
    'HRV': 'Croatia',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Ireland',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JPN': 'Japan',
    'KOR': 'Korea',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MEX': 'Mexico',
    'MLT': 'Malta',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'PER': 'Peru',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'SAU': 'Saudi Arabia',
    'SVK': 'Slovak Republic',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'TUR': 'Turkey',
    'USA': 'United States',
    'ZAF': 'South Africa'
};

// export default {
//     'AL': 'Alabama',
//     'AK': 'Alaska',
//     'AS': 'American Samoa',
//     'AZ': 'Arizona',
//     'AR': 'Arkansas',
//     'CA': 'California',
//     'CO': 'Colorado',
//     'CT': 'Connecticut',
//     'DE': 'Delaware',
//     'DC': 'District Of Columbia',
//     'FM': 'Federated States Of Micronesia',
//     'FL': 'Florida',
//     'GA': 'Georgia',
//     'GU': 'Guam',
//     'HI': 'Hawaii',
//     'ID': 'Idaho',
//     'IL': 'Illinois',
//     'IN': 'Indiana',
//     'IA': 'Iowa',
//     'KS': 'Kansas',
//     'KY': 'Kentucky',
//     'LA': 'Louisiana',
//     'ME': 'Maine',
//     'MH': 'Marshall Islands',
//     'MD': 'Maryland',
//     'MA': 'Massachusetts',
//     'MI': 'Michigan',
//     'MN': 'Minnesota',
//     'MS': 'Mississippi',
//     'MO': 'Missouri',
//     'MT': 'Montana',
//     'NE': 'Nebraska',
//     'NV': 'Nevada',
//     'NH': 'New Hampshire',
//     'NJ': 'New Jersey',
//     'NM': 'New Mexico',
//     'NY': 'New York',
//     'NC': 'North Carolina',
//     'ND': 'North Dakota',
//     'MP': 'Northern Mariana Islands',
//     'OH': 'Ohio',
//     'OK': 'Oklahoma',
//     'OR': 'Oregon',
//     'PW': 'Palau',
//     'PA': 'Pennsylvania',
//     'PR': 'Puerto Rico',
//     'RI': 'Rhode Island',
//     'SC': 'South Carolina',
//     'SD': 'South Dakota',
//     'TN': 'Tennessee',
//     'TX': 'Texas',
//     'UT': 'Utah',
//     'VT': 'Vermont',
//     'VI': 'Virgin Islands',
//     'VA': 'Virginia',
//     'WA': 'Washington',
//     'WV': 'West Virginia',
//     'WI': 'Wisconsin',
//     'WY': 'Wyoming'
// };
